# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e190214c-8f8c-4b03-9015-e3e1f5b63cdb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2365561d-2d74-459a-9610-dbc5d08be90e".device = "/dev/disk/by-uuid/2365561d-2d74-459a-9610-dbc5d08be90e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A1C8-037C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/Data" =
    { device = "/dev/disk/by-uuid/2ef0d2ba-062b-4c9e-83e6-32574fb65b2b";
      fsType = "ext4";
    };

  fileSystems."/mnt/Media" =
    { device = "/dev/disk/by-uuid/c2394864-c0bb-4d2b-a939-79f843e9507c";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
